### ISSUE TITLE
Some feedback for Training Module I

### ISSUE THREAD

**Issue by AviatorMoser** [vanzod/BioHPC_training_notes#1]
1) Did you attempt to run MySQL Community Server 5.6 before installing and running MariaDB? Were there any conflicts present from leftover files? (to answer the question for MySQL 5.4 -- yes, at the time MariaDB would conflict with leftover files generated by MySQL Community Server).

2) On the ACL step -- what setfacl flag is needed to place a default ACL on any newly created files in that directory?

3) When adding a new disk -- it is not necessary to create a partition first on the empty drive before adding it to the volume group and extending the logical volume.

Great work!

**Comment by vanzod** [comment]
>     1. Did you attempt to run MySQL Community Server 5.6 before installing and running MariaDB? Were there any conflicts present from leftover files? (to answer the question for MySQL 5.4 -- yes, at the time MariaDB would conflict with leftover files generated by MySQL Community Server).

Yes, hence the need to request `yum` to remove all the dependencies. In production a backup of the database would also be advised (if not necessary) followed by a restore in MariaDB.

>     2. On the ACL step -- what setfacl flag is needed to place a default ACL on any newly created files in that directory?

To make ACL permissions inherited by newly created child files and directories, a default permission can be specified with the `-d` flag. In the exercise we only provided read and execute permissions to the user, so this flag would be unnecessary.

>     3. When adding a new disk -- it is not necessary to create a partition first on the empty drive before adding it to the volume group and extending the logical volume.

Got it. Thanks
